# docker run -d -it -v /path/on/host:/data -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-pvc
      containers:
      - name: minecraft-server
        image: itzg/minecraft-server:latest
        resources:
          limits:
            memory: 6Gi
          requests:
            memory: 4Gi
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MOTD
            value: Hilton Network AoF4 1.0.1
          - name: TYPE
            value: CURSEFORGE
          - name: CF_SERVER_MOD
            value: AllofFabric4Server-1.0.1.zip
          - name: MEMORY
            value: " "
          - name: JVM_XX_OPTS
            value: "-XX:MaxRAMPercentage=75"
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data
