# docker run -d -it -v /path/on/host:/data -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-pvc
      containers:
      - name: minecraft-server
        image: itzg/minecraft-server:latest
        resources:
          limits:
            memory: 5Gi
            cpu: 3
          requests:
            memory: 5Gi
            cpu: 2
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MOTD
            value: Hilton Network AoF5 1.5.1
          - name: TYPE
            value: CURSEFORGE
          - name: CF_SERVER_MOD
            value: All-of-Fabric-5-Server-1.5.1.zip 
          - name: MEMORY
            value: " "
          - name: JVM_XX_OPTS
            value: "XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UseCompressedOops -XX:-UsePerfData -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=50 -XX:G1HeapRegionSize=1 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 -XX:MaxRAMPercentage=90"
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
