apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  ports:
    - port: 25565
      targetPort: 25565
      name: minecraft-port
  externalIPs:
   - 10.0.0.101
  selector:
    app: minecraft-server
