apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  ports:
    - port: 25565
      targetPort: 25565
      name: minecraft-port
    - port: 80
      targetPort: 80
      name: http
    - port: 446
      targetPort: 446
      name: https
  externalIPs:
   - 10.0.0.102
  selector:
    app: minecraft-server
